<?php

use Illuminate\Foundation\Testing\LazilyRefreshDatabase;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Schema;

// Feature: fortify-auth-migration — schema-invariance regression test.
// Proves the Fortify migration made NO schema changes to the `users` or
// `password_resets` tables, that the 2fa_* columns are intact, and that
// Fortify's native two_factor_*/passkeys scaffolding was NOT added.
// Validates: Requirements 10.2, 12.1

uses(LazilyRefreshDatabase::class);

beforeEach(function () {
    // Pin the cache to the in-memory array store, mirroring the sibling Fortify
    // tests. Schema assertions do not need the cache, but keep it consistent.
    config(['cache.default' => 'array']);
    Cache::store('array')->flush();
});

/*
|--------------------------------------------------------------------------
| R12.1 — the `users` table retains its auth-relevant columns unchanged
|--------------------------------------------------------------------------
*/

it('keeps the users table and all auth-relevant columns intact', function () {
    // R12.1 — no schema change: the users table exists and still carries every
    // column consumed by auth per design.md Data Models (verified against the
    // create_users_table, add_status, add_register_source, and add_2fa
    // migrations).
    expect(Schema::hasTable('users'))->toBeTrue();

    expect(Schema::hasColumns('users', [
        'id',
        'name',
        'username',
        'email',
        'password',
        'email_verified_at',
        'remember_token',
        'app_register_ip',
        'status',
        '2fa_enabled',
        '2fa_secret',
        '2fa_backup_codes',
        '2fa_setup_at',
    ]))->toBeTrue();
});

/*
|--------------------------------------------------------------------------
| R12.1 — the `password_resets` broker table is unchanged
|--------------------------------------------------------------------------
*/

it('keeps the password_resets table with its broker columns intact', function () {
    // R12.1 — the passwords broker table exists with the columns defined by
    // create_password_resets_table (email, token, created_at). Fortify reuses
    // this same broker; no change.
    expect(Schema::hasTable('password_resets'))->toBeTrue();

    expect(Schema::hasColumns('password_resets', [
        'email',
        'token',
        'created_at',
    ]))->toBeTrue();
});

/*
|--------------------------------------------------------------------------
| R10.2 — the four 2fa_* columns are preserved
|--------------------------------------------------------------------------
*/

it('preserves the four 2fa_* columns on the users table', function () {
    // R10.2 — the migration leaves the 2fa_* column definitions unchanged.
    expect(Schema::hasColumns('users', [
        '2fa_enabled',
        '2fa_secret',
        '2fa_backup_codes',
        '2fa_setup_at',
    ]))->toBeTrue();
});

/*
|--------------------------------------------------------------------------
| R10.2 / R12.1 — Fortify's native 2FA columns were NOT added
|--------------------------------------------------------------------------
*/

it('does not add Fortify native two_factor_* columns to the users table', function () {
    // R10.2 — Fortify's two-factor feature is disabled and its generated
    // two-factor columns migration was deleted (task 1.1). Pixelfed keeps its
    // own 2fa_* columns, so Fortify's native columns must be absent.
    expect(Schema::hasColumn('users', 'two_factor_secret'))->toBeFalse();
    expect(Schema::hasColumn('users', 'two_factor_recovery_codes'))->toBeFalse();
});

/*
|--------------------------------------------------------------------------
| R12.1 — no Fortify passkeys table was created
|--------------------------------------------------------------------------
*/

it('does not create a Fortify passkeys table', function () {
    // R12.1 — the passkeys migration generated by fortify:install was deleted
    // (task 1.1); the table must not exist.
    expect(Schema::hasTable('passkeys'))->toBeFalse();
});
