#!/bin/bash

declare service="${PF_SERVICE:=worker}"
declare user="${PF_USER:=www-data}"

exec docker compose exec \
    --user "${user}" \
    --env TERM \
    --env COLORTERM \
    "${service}" \
    php artisan "${@}"
