#!/bin/bash

declare root="${PWD}"

if command -v git &>/dev/null; then
    root=$(git rev-parse --show-toplevel)
fi

exec docker run \
    --rm \
    --interactive \
    --tty \
    --volume "${root}:/var/www" \
    --workdir /var/www \
    ghcr.io/jippi/dottie \
    "$@"
