#!/bin/bash

declare project_root="${PWD}"

if command -v git &>/dev/null; then
    project_root=$(git rev-parse --show-toplevel)
fi

exec docker run \
    --rm \
    --interactive \
    --tty \
    --volume "${project_root}:/var/www" \
    --volume "/tmp:/tmp" \
    --workdir /var/www \
    ghcr.io/jippi/dottie \
    "$@"
