<?xml version="1.0" encoding="UTF-8"?>
<!-- RSS generated by pixelfed v{{config('pixelfed.version')}} on {{$now}} -->
<rss version="2.0">
	<channel>
		<title>{{ $account['username'] }}'s Portfolio</title>
		<link>{{ $portfolioUrl }}</link>
		<description>The pixelfed portfolio of {{ $account['username'] }} with the {{ count($feed) }} most recent posts</description>
		<pubDate>{{ $now }}</pubDate>
		<language>en-us</language>
@foreach($feed as $p)
			<item>
				<title>{{$p['title']}}</title>
				<description>{{$p['description']}}</description>
				<guid>{{$p['url']}}</guid>
				<link>{{$p['url']}}</link>
				<pubDate>{{$p['pubDate']}}</pubDate>
			</item>
@endforeach
	</channel>
</rss>
