type: laravel
docroot: public
php_version: "8.1"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.4"
disable_settings_management: true
web_environment:
  - DB_CONNECTION=mysql
  - DB_HOST=ddev-pixelfed-db
  - DB_DATABASE=db
  - DB_USERNAME=db
  - DB_PASSWORD=db
  - REDIS_HOST=ddev-pixelfed-redis
  - MAIL_DRIVER=smtp
  - MAIL_HOST=localhost
  - MAIL_PORT=1025
  - MAIL_USERNAME=null
  - MAIL_PASSWORD=null
  - MAIL_ENCRYPTION=null
  - APP_KEY=placeholder
  - APP_NAME=PixelfedTest
  - APP_ENV=local
  - APP_KEY=base64:lwX95GbNWX3XsucdMe0XwtOKECta3h/B+p9NbH2jd0E=
  - APP_DEBUG=true
  - APP_URL=https://pixelfed.ddev.site
  - APP_DOMAIN=pixelfed.ddev.site
  - ADMIN_DOMAIN=pixelfed.ddev.site
  - SESSION_DOMAIN=pixelfed.ddev.site
  - "TRUST_PROXIES=*"
  - LOG_CHANNEL=stack
