name: Auto Rebase PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       (contains(github.event.issue.labels.*.name, 'autorebase') ||
        contains(github.event.issue.labels.*.name, 'autosquash'))) ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request != '' &&
       (contains(github.event.comment.body, '/rebase') ||
        contains(github.event.comment.body, '/autosquash')))
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        with:
          autosquash: ${{ (github.event_name == 'pull_request' &&
                           contains(github.event.issue.labels.*.name, 'autosquash')) ||
                          (github.event_name == 'issue_comment' &&
                           (contains(github.event.comment.body, '/autosquash') ||
                            contains(github.event.comment.body, '/rebase-autosquash'))) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
