name: PHP - Larastan
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5' # Or your desired PHP version
          extensions: mbstring, pdo_mysql # Add necessary extensions
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse
