name: PHP - Psalm

on:
  push:
    branches:
      - dev
      - staging
  pull_request:
    branches:
      - dev
      - staging

jobs:
  psalm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      - name: Run Psalm
        run: ./vendor/bin/psalm --output-format=github --shepherd
        